name: .NET

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore and build
      run: |
        cd hotel
        dotnet restore
        dotnet build --no-restore --configuration Release
        dotnet test --no-build --configuration Release --verbosity normal